"""
Datos de demostración para probar el sistema sin conexión a internet.
En producción (tu máquina), todos los datos vienen de APIs reales.
"""
from datetime import datetime

DEMO_MARKET_OVERVIEW = {
    "S&P 500": {"price": 5487.21, "change_pct": 0.38, "trend": "▲"},
    "NASDAQ": {"price": 19654.83, "change_pct": 0.61, "trend": "▲"},
    "DOW JONES": {"price": 42215.10, "change_pct": 0.15, "trend": "▲"},
    "EURO STOXX 50": {"price": 5012.44, "change_pct": -0.22, "trend": "▼"},
    "IBEX 35": {"price": 11892.10, "change_pct": 0.45, "trend": "▲"},
    "ORO": {"price": 3347.80, "change_pct": 0.82, "trend": "▲"},
    "PETRÓLEO WTI": {"price": 74.33, "change_pct": -1.21, "trend": "▼"},
    "EUR/USD": {"price": 1.1285, "change_pct": 0.11, "trend": "▲"},
}

DEMO_STOCKS = [
    {
        "symbol": "NVDA", "current_price": 138.85, "rsi": 64.2,
        "macd": 2.14, "macd_signal": 1.82, "macd_histogram": 0.32,
        "bb_upper": 145.20, "bb_lower": 118.60, "sma50": 128.40, "sma200": 105.20,
        "change_5d_pct": 5.8, "change_20d_pct": 12.3,
        "signals": ["MACD cruce alcista", "Por encima de SMA50 y SMA200 (Golden Cross)"],
        "technical_score": 2, "action": "BUY",
    },
    {
        "symbol": "AAPL", "current_price": 213.50, "rsi": 58.1,
        "macd": 0.82, "macd_signal": 0.91, "macd_histogram": -0.09,
        "bb_upper": 220.10, "bb_lower": 195.40, "sma50": 205.30, "sma200": 195.10,
        "change_5d_pct": 1.2, "change_20d_pct": 3.4,
        "signals": ["Por encima de SMA50 y SMA200"],
        "technical_score": 1, "action": "WATCH",
    },
    {
        "symbol": "MSFT", "current_price": 444.72, "rsi": 52.3,
        "macd": -0.45, "macd_signal": -0.38, "macd_histogram": -0.07,
        "bb_upper": 462.00, "bb_lower": 420.15, "sma50": 438.20, "sma200": 410.50,
        "change_5d_pct": 0.8, "change_20d_pct": 2.1,
        "signals": [], "technical_score": 0, "action": "HOLD",
    },
    {
        "symbol": "ASML", "current_price": 712.40, "rsi": 28.5,
        "macd": -8.20, "macd_signal": -5.10, "macd_histogram": -3.10,
        "bb_upper": 780.00, "bb_lower": 700.80, "sma50": 745.30, "sma200": 720.10,
        "change_5d_pct": -8.2, "change_20d_pct": -15.3,
        "signals": ["RSI sobrevendido (señal de compra)", "Precio bajo Bollinger inferior"],
        "technical_score": 2, "action": "BUY",
    },
    {
        "symbol": "SPY", "current_price": 547.21, "rsi": 61.4,
        "macd": 1.82, "macd_signal": 1.44, "macd_histogram": 0.38,
        "bb_upper": 560.40, "bb_lower": 525.10, "sma50": 535.20, "sma200": 510.80,
        "change_5d_pct": 1.8, "change_20d_pct": 4.2,
        "signals": ["Golden Cross: tendencia alcista", "MACD cruce alcista"],
        "technical_score": 2, "action": "BUY",
    },
]

DEMO_CRYPTO_GLOBAL = {
    "total_market_cap_eur": 3_280_000_000_000,
    "total_volume_eur": 112_000_000_000,
    "btc_dominance": 57.8,
    "eth_dominance": 11.2,
    "active_coins": 17482,
    "market_cap_change_24h": 1.84,
}

DEMO_CRYPTO_COINS = [
    {"id": "bitcoin", "symbol": "BTC", "name": "Bitcoin",
     "price": 104_280.0, "market_cap": 2_070_000_000_000,
     "market_cap_rank": 1, "volume_24h": 48_000_000_000,
     "change_24h": 2.1, "change_7d": 5.8, "change_30d": 18.4,
     "ath": 108_786.0, "ath_change_pct": -4.1},
    {"id": "ethereum", "symbol": "ETH", "name": "Ethereum",
     "price": 2_692.0, "market_cap": 325_000_000_000,
     "market_cap_rank": 2, "volume_24h": 22_000_000_000,
     "change_24h": 3.4, "change_7d": 12.1, "change_30d": -8.2,
     "ath": 4_878.26, "ath_change_pct": -44.8},
    {"id": "solana", "symbol": "SOL", "name": "Solana",
     "price": 165.42, "market_cap": 84_000_000_000,
     "market_cap_rank": 5, "volume_24h": 5_400_000_000,
     "change_24h": 4.8, "change_7d": 15.3, "change_30d": -12.1,
     "ath": 259.96, "ath_change_pct": -36.4},
    {"id": "cardano", "symbol": "ADA", "name": "Cardano",
     "price": 0.8812, "market_cap": 31_000_000_000,
     "market_cap_rank": 9, "volume_24h": 1_200_000_000,
     "change_24h": -1.2, "change_7d": 8.4, "change_30d": -25.3,
     "ath": 3.09, "ath_change_pct": -71.5},
    {"id": "chainlink", "symbol": "LINK", "name": "Chainlink",
     "price": 16.84, "market_cap": 11_200_000_000,
     "market_cap_rank": 15, "volume_24h": 820_000_000,
     "change_24h": 5.2, "change_7d": 18.7, "change_30d": 22.1,
     "ath": 52.70, "ath_change_pct": -68.0},
]

DEMO_NEWS = [
    {"title": "Fed mantiene tipos en 4.25-4.5% y señala posibles bajadas en H2 2026",
     "url": "https://example.com/1", "source": "Reuters",
     "sentiment": "POSITIVE", "sentiment_score": 0.45,
     "summary": "La Reserva Federal mantuvo los tipos de interés sin cambios y sugirió que podría empezar a bajarlos en la segunda mitad del año si la inflación continúa moderándose.",
     "related_symbols": ["MARKET", "MSFT", "AAPL"], "published_at": datetime.now().isoformat()},
    {"title": "NVDA bate expectativas: ingresos de IA superan los $44B en Q1 2026",
     "url": "https://example.com/2", "source": "Yahoo Finance",
     "sentiment": "POSITIVE", "sentiment_score": 0.82,
     "summary": "NVIDIA reportó ingresos récord impulsados por la demanda masiva de GPUs H100/H200 para centros de datos de IA.",
     "related_symbols": ["NVDA"], "published_at": datetime.now().isoformat()},
    {"title": "Bitcoin supera los $104,000 tras rumores de nuevo ETF soberano",
     "url": "https://example.com/3", "source": "CoinDesk",
     "sentiment": "POSITIVE", "sentiment_score": 0.68,
     "summary": "BTC alcanzó máximos de 3 semanas ante especulaciones de que un fondo soberano asiático estaría acumulando posiciones.",
     "related_symbols": ["BTC"], "published_at": datetime.now().isoformat()},
    {"title": "Preocupación por datos de empleo en EEUU: tasa de paro sube al 4.3%",
     "url": "https://example.com/4", "source": "Bloomberg",
     "sentiment": "NEGATIVE", "sentiment_score": -0.38,
     "summary": "Los datos de empleo muestran una ligera debilidad que podría acelerar los recortes de tipos de la Fed.",
     "related_symbols": ["MARKET"], "published_at": datetime.now().isoformat()},
    {"title": "Mercado inmobiliario español: precios suben 8.2% anual en Mayo 2026",
     "url": "https://example.com/5", "source": "El Confidencial",
     "sentiment": "NEUTRAL", "sentiment_score": 0.12,
     "summary": "El mercado de la vivienda en España mantiene su fortaleza con escasez de oferta en grandes ciudades.",
     "related_symbols": ["REAL_ESTATE"], "published_at": datetime.now().isoformat()},
]

DEMO_GITHUB_TOOLS = [
    {"name": "backtrader", "full_name": "mementum/backtrader",
     "description": "Python Backtesting library for trading strategies",
     "html_url": "https://github.com/mementum/backtrader",
     "stargazers_count": 15200, "forks_count": 3800,
     "language": "Python", "topics": ["backtesting", "trading", "python"],
     "category": "backtesting", "relevance_score": 0.95,
     "recommendation": "Úsalo para testear estrategias antes de invertir dinero real. Soporta acciones, futuros y forex."},
    {"name": "QuantLib", "full_name": "lballabio/QuantLib",
     "description": "The QuantLib C++ library for quantitative finance",
     "html_url": "https://github.com/lballabio/QuantLib",
     "stargazers_count": 5400, "forks_count": 2100,
     "language": "C++", "topics": ["quantitative-finance", "derivatives"],
     "category": "analytics", "relevance_score": 0.82,
     "recommendation": "Para valoración de derivados y análisis de renta fija. Avanzado."},
    {"name": "freqtrade", "full_name": "freqtrade/freqtrade",
     "description": "Free, open source crypto trading bot",
     "html_url": "https://github.com/freqtrade/freqtrade",
     "stargazers_count": 32100, "forks_count": 6500,
     "language": "Python", "topics": ["crypto-trading", "algorithmic-trading", "bot"],
     "category": "algo_trading", "relevance_score": 0.91,
     "recommendation": "Bot de trading crypto con backtesting integrado y múltiples exchanges. Integra perfectamente con este sistema."},
    {"name": "vectorbt", "full_name": "polakowo/vectorbt",
     "description": "Find your trading edge, using the fastest engine for backtesting",
     "html_url": "https://github.com/polakowo/vectorbt",
     "stargazers_count": 4200, "forks_count": 680,
     "language": "Python", "topics": ["backtesting", "portfolio", "technical-analysis"],
     "category": "backtesting", "relevance_score": 0.88,
     "recommendation": "Backtesting vectorizado ultrarrápido. Ideal para optimizar parámetros de estrategias."},
    {"name": "portfolio-analytics", "full_name": "quantopian/pyfolio",
     "description": "Portfolio and risk analytics in Python",
     "html_url": "https://github.com/quantopian/pyfolio",
     "stargazers_count": 5700, "forks_count": 1680,
     "language": "Python", "topics": ["portfolio", "analytics", "risk"],
     "category": "portfolio", "relevance_score": 0.87,
     "recommendation": "Análisis de riesgo y rendimiento del portfolio. Genera informes completos con Sharpe ratio, drawdowns, etc."},
]
